---
title: "Copying files to the `src` directory"
author: "Daniel Vartanian"
format: html
---

## Overview

This document contains some code to facilitate the copying of files from the root directory to the `src` directory.

## Setup

```{r}
#| eval: false

library(checkmate, quietly = TRUE)
library(here, quietly = TRUE)
library(readr, quietly = TRUE)
library(stringr, quietly = TRUE)
```

## Copying files

```{r}
files_to_copy <- 
  c(
    list.files(here::here("png"), full.names = TRUE),
    here::here("README.md")
  ) |>
  stringr::str_replace(paste0(here::here(), "/"), "")
```

```{r}
for (i in files_to_copy) {
  pattern <- ".*(?=/)"
  
  if (stringr::str_detect(i, pattern)) {
    dir <- stringr::str_extract(i, ".*(?=/)")
    if (!dir.exists(here::here("src", dir))) dir.create(here::here("src", dir))
    to <- here::here("src", dir, basename(i))
  } else {
    to <- here::here("src", basename(i))
  }
  
  file.copy(
    from = here::here(i), 
    to = to, 
    overwrite = TRUE
  )
}
```

```{r}
fix_readme_paths <- function(file) {
  checkmate::assert_string(file)
  checkmate::assert_file_exists(file)
  
  data <- 
    file |>
    readr::read_lines(skip = 3)
  
  readr::write_lines(
    x = data,
    file = file
  )
}
```

```{r}
fix_readme_paths(here::here("src", "README.md"))
```
